/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NetworkNode } from "./utils/models/network-node";
import { NetworkLink } from "./utils/models/network-link";
export namespace Components {
    interface NetworkGraph {
        "links": NetworkLink[];
        "nodes": NetworkNode[];
    }
    interface NetworkGraphSvg {
        "links": NetworkLink[];
        "nodes": NetworkNode[];
    }
}
declare global {
    interface HTMLNetworkGraphElement extends Components.NetworkGraph, HTMLStencilElement {
    }
    var HTMLNetworkGraphElement: {
        prototype: HTMLNetworkGraphElement;
        new (): HTMLNetworkGraphElement;
    };
    interface HTMLNetworkGraphSvgElement extends Components.NetworkGraphSvg, HTMLStencilElement {
    }
    var HTMLNetworkGraphSvgElement: {
        prototype: HTMLNetworkGraphSvgElement;
        new (): HTMLNetworkGraphSvgElement;
    };
    interface HTMLElementTagNameMap {
        "network-graph": HTMLNetworkGraphElement;
        "network-graph-svg": HTMLNetworkGraphSvgElement;
    }
}
declare namespace LocalJSX {
    interface NetworkGraph {
        "links"?: NetworkLink[];
        "nodes"?: NetworkNode[];
    }
    interface NetworkGraphSvg {
        "links"?: NetworkLink[];
        "nodes"?: NetworkNode[];
    }
    interface IntrinsicElements {
        "network-graph": NetworkGraph;
        "network-graph-svg": NetworkGraphSvg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "network-graph": LocalJSX.NetworkGraph & JSXBase.HTMLAttributes<HTMLNetworkGraphElement>;
            "network-graph-svg": LocalJSX.NetworkGraphSvg & JSXBase.HTMLAttributes<HTMLNetworkGraphSvgElement>;
        }
    }
}
